#Introduction to Linear Regression

In [1]:
import torch
import numpy as np

###Training Data


In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


###Linear regression model from scratch

In [9]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.8188,  1.4913, -0.9552],
        [ 1.3887, -1.6437,  1.5994]], requires_grad=True)
tensor([-1.1643,  1.2736], requires_grad=True)


In [10]:
def model(x):
  return x @ w.t() + b

In [12]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[117.4529,  61.2969],
        [143.4498,  85.3638],
        [214.5052,  -5.3985],
        [111.1384, 131.4226],
        [131.6353,  51.2586]], grad_fn=<AddBackward0>)


In [13]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


###Loss function


In [14]:
# MSE Loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [15]:
# Compute Loss
loss = mse(preds, targets)
print(loss)

tensor(5854.2217, grad_fn=<DivBackward0>)


###Compute gradients

In [16]:
# Compute gradients
loss.backward()

In [17]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.8188,  1.4913, -0.9552],
        [ 1.3887, -1.6437,  1.5994]], requires_grad=True)
tensor([[ 5909.1787,  5798.5112,  3496.2305],
        [-1828.3877, -4589.4985, -2130.0649]])


###Adjust weights and biases to reduce the loss

In [18]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [19]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(5854.2217, grad_fn=<DivBackward0>)


In [22]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


###Train the model using gradient descent for multiple epochs

In [26]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [27]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(179.6727, grad_fn=<DivBackward0>)


In [28]:
# Predictions
preds

tensor([[ 55.3225,  69.8850],
        [ 93.3636,  93.0321],
        [ 96.2781, 151.0154],
        [ 12.7456,  32.5962],
        [125.9659, 108.6752]], grad_fn=<AddBackward0>)

In [29]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])